Add image list/detail endpoints
ImageMarkup/isic pull request #271
Opened 2021-08-03 18:35 UTC by danlamanna

2021-08-07 02:19 UTC, danlamanna commented
@brianhelba this should do lookups based on isic id, and it rounds ages appropriately.

2021-08-07 16:56 UTC, danlamanna commented on isic/ingest/tests/factories.py
> +    metadata = factory.Dict({})
@brianhelba This is causing every the tests to fail, but works for `test_core_api_image_ages_are_always_rounded` where I set `accession__metadata__age`. Have you done this any other way?

2021-08-07 21:14 UTC, danlamanna commented on isic/ingest/tests/factories.py
> +    metadata = factory.Dict({})
fixed.

2021-08-10 16:48 UTC, brianhelba requested changes

2021-08-10 16:52 UTC, brianhelba commented
I pushed one commit adding some metadata content to `AccessionFactory`.

2021-08-11 03:40 UTC, danlamanna commented
> I pushed one commit adding some metadata content to AccessionFactory.

@brianhelba Not sure why your commit broke, it also breaks other test(s?) that assume metadata is blank. Can you take a look, or back it out of this PR which is otherwise working?

2021-08-11 23:05 UTC, brianhelba approved these changes

2021-08-11 23:07 UTC, brianhelba approved these changes

2021-08-11 23:07 UTC, merged